site_name: dekimpew docs
theme: 
  name: material
  palette:
    - scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

markdown_extensions:
  - def_list
  - sane_lists
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
- Home: index.md
- Homelab: 
  - Setup: homelab/index.md
  - Topology: homelab/topology.md
- vSphere Supervisor: 
  - Introduction: tanzu/index.md
  #- WCP with NSX: tanzu/nsx_for_wcp.md
  - External OIDC on Supervisor: tanzu/wcp_oidc.md
  - RBAC options on Supervisor: tanzu/rbac_on_wcp.md
  - Issues with Supervisor: tanzu/wcp_issues.md
- Kubernetes: 
  - Introduction: k8s/index.md
  - Custom HPA metrics: k8s/custom_hpa.md
  #- AVI with kubeadm: k8s/avi_with_k8s.md